# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='cerated_time',
            new_name='created_time',
        ),
    ]
